[project]
name = "alc-sat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lxml>=6.0.1",
    "lxml-stubs>=0.5.1",
    "ontolearn",
    "owlapy>=1.5.1",
    "owlready2>=0.48",
    "pytest>=8.4.2",
    "python-sat>=1.8.dev20",
]

[tool.uv.sources]
ontolearn = { git = "https://github.com/SAT-based-Concept-Learning/Ontolearn" }
